---
title: "NYC Restaurant Inspection Results"
output: 
  html_document:
    toc: true
    toc_float: true 
---
```{r, message = FALSE}
library(dplyr)
library(tidyverse)
library(plotly)
library(httr)
library(jsonlite)
```

```{r loading_restaurant_inspection, include = FALSE}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() 
```

```{r cleaning_inspection_data}
data(nyc_inspections)

nyc_inspections_cleaned = 
  nyc_inspections |> 
  janitor::clean_names()|>
  select(
    boro, zipcode, inspection_date, dba, cuisine_description, score, grade,latitude, longitude) |>

rename (restaurant = dba)|>
filter(
    !is.na(grade))
```

```{r inspection_scatter_plot}
nyc_inspections_cleaned |>
  mutate(text_label = str_c("\nGrade:", grade, "\nrestaurant:", restaurant)) |> 
  plot_ly(
    x = ~latitude, y = ~longitude, type = "scatter", mode = "markers",
    color = ~grade, text = ~text_label, alpha = 0.5)
```



